require("dotenv").config();
const express=require("express"),cors=require("cors"),helmet=require("helmet"),rateLimit=require("express-rate-limit");
const {createMainnetApi}=require("./src/mainnet-api");
const app=express(),api=createMainnetApi(),PORT=Number(process.env.PORT||3000);
const origins=String(process.env.ALLOWED_ORIGINS||"").split(",").map(v=>v.trim()).filter(Boolean);
app.disable("x-powered-by");app.set("trust proxy",1);app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin(origin,cb){if(!origin||origins.length===0||origins.includes(origin))return cb(null,true);cb(new Error("Origin is not allowed."));},methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type","Authorization","X-API-Key"]}));
app.use(express.json({limit:"100kb"}));app.use(rateLimit({windowMs:60000,limit:120,standardHeaders:"draft-7",legacyHeaders:false}));
app.get("/",(_q,r)=>r.json({service:"albukhr-api",status:"ok",network:"mainnet",version:"2.0.0"}));
app.get("/health",async(_q,r)=>{try{const h=await api.health();r.status(h.status==="ok"?200:503).json(h);}catch{r.status(503).json({status:"error",network:"mainnet",error:"Health check failed."});}});
app.get("/supabase-status",async(_q,r)=>{try{const s=await api.databaseStatus();r.status(s.status==="ok"?200:503).json(s);}catch{r.status(503).json({status:"error",network:"mainnet",error:"Database status unavailable."});}});
app.get("/mainnet-status",api.requireOpsKey,async(_q,r)=>{try{r.json(await api.mainnetStatus());}catch{r.status(503).json({success:false,network:"mainnet",error:"Mainnet Horizon status unavailable."});}});
app.get("/wallet-status",api.requireOpsKey,async(_q,r)=>{try{r.json(await api.walletStatus());}catch{r.status(503).json({success:false,network:"mainnet",error:"Wallet status unavailable."});}});
for(const route of ["/approve","/complete","/withdraw","/pay-withdraw","/api/pi-project-treasury-payment"])app.post(route,api.financialUnavailable);
app.use((e,_q,r,_n)=>{if(e?.message==="Origin is not allowed.")return r.status(403).json({success:false,error:e.message});console.error("[ALBUKHR API]",e);r.status(500).json({success:false,error:"Internal server error."});});
app.listen(PORT,()=>console.log(`ALBUKHR MAINNET API v2.0.0 running on ${PORT}`));
